### ISSUE TITLE
Feature request: include name / date of source DAT from No-Intro, etc. in metadata comments

### ISSUE THREAD

**Issue by burkasaurusrex** [linuxserver/emulatorjs#10]
Given how regularly DATs have been updated (historically more so than recently), it would be helpful to know which files and dates the hashes were pulled from. Maybe a comment header for each `json`?

Additionally, what's the best way to handle different / successive hashes for the same game? I think the way the `json` is structured today, you could create an additional dictionary entry copying the same metadata entries. Ideally there would be some way to have the same set of metadata entries point to multiple hashes, but I'm guessing that might be a heavy lift.

**Comment by thelamer** [comment]
I intentionally forked off at a point in time, these databases should live on their own as they will not have the restrictions that no-intro imposes on their submissions. 
Basically I don't care about a couple megs of additional json in the repo (hell it is not even minified). 
Entries have a ref concept see this: https://github.com/linuxserver/emulatorjs/blob/master/metadata/snes.json#L647

The end goal is to link a game to art assets for downloading. So if there are like 40 different versions of some rom out there then people can just link up the identification data from the UI and the resulting ref code will be in their `/data/metadata/` in the container, it can be submitted as an issue or a PR and I will just put it in the main data (within reason). 

When I initially setup my local setup using clean sets I found tons of oddities which is why the ref concept exists.

**Comment by thelamer** [comment]
Since this issue was opened I have referenced all variants I could to international roms to ones with art and added logogs for most systems/games. 
It is not perfect, but as stated earlier I need help here.
