### ISSUE TITLE
Going back to main menu from game

### ISSUE THREAD

**Issue by MrJay84** [linuxserver/emulatorjs#17]
Pressing F1 to return the the console/game menu is stuck on the game stage/doesn't return to main page. The back option on the browser must be used.

![Screenshot 2022-01-05 141209](https://user-images.githubusercontent.com/92555921/148231411-c7148d56-eafb-4190-8e5d-c116f5bb14bb.jpg)
.

**Comment by thelamer** [comment]
I have not found a way to reliably detect wasm quit without running a stateful loop. This is expected behavior and why there is a 1 second delay when you hit back, it calls the program to dump sram when you navigate away to store saves browser side. I do want this though and have tinkered with it in the past.

**Comment by MrJay84** [comment]
Ah okay so it's not a bug. Thanks for the quick response Ryan. I assumed I was doing something wrong.

⁣Get BlueMail for Android ​

**Comment by thelamer** [comment]
I don't think this is going to be possible without doing heavy mods to Retroarch emscripten codebase which I really do not want to maintain. I think the back button is the only reliable method.

**Comment by rrgeorge** [comment]
With the pr I submitted for gamepad menu control, after you quit retroarch, you can triple press the Home button on your gamepad to return to the main page.
