### ISSUE TITLE
[Feature Request] Option to order rom by title instead of filename

### ISSUE THREAD

**Issue by nixxou** [linuxserver/emulatorjs#34]
I have my arcade romset with the default name like stg.zip, stinger.zip...
So the first letter match, but it's all mess up, like Strike Gunner STG is show after Stinger.
I've got the same issue with nds game ordered like that : 2612 - Race Driver - Grid (Europe) (En,Fr,De,Es,It) [b].nds
Yeah, i could probably get ride of it with a rename, but i would very much like keep my file intact as much as possible

Could you please add an option (i guess that should probably be by default) to sort game by their real title (you got when you download art, right ?), not their filename ? If their is no art and the rom is Unidentified, yeah, use their filename, but it would be so much better to use the real title if available.

**Comment by nixxou** [comment]
While i'm at it, i can suggest some other improvements.

So the game browser layout look like this : 

![image](https://user-images.githubusercontent.com/45721836/154010674-56603613-653b-4a61-b958-637aeb660df1.png)
For us, western player, japanese logo are not really simple to read and while it's beautiful, it could be nice to have a key that allow to identify and show up the rom name as text over the tv. (or maybe with a text over the video player, on top, with a fade after 1 or 2 sec)

Up and down allow to browse between game, but it would be great to change the sorting with left and right and switch between alphabetic, last 10 played and favorites only (with a keybind to mark a game as favorite and a tiny star to add).

An other feature related to game sorting that could be interesting is to be able to switch between logo and full text. Logo are nice, but when you look a game in a really big collection, it could be nice to switch to text and have over 20/25 titles to show up at once. instead of 9.
![image](https://user-images.githubusercontent.com/45721836/154030095-932a457c-e901-4fa1-950d-332f424d778b.png)

**Comment by LostOnTheLine** [comment]
How is the sorting by title instead of by filename a preferable solution? I mean I understand what you are saying, but your reasoning is that you named your games by something that is not their name & you don't want to change how you named them correct?

I understand the things I want aren't common & don't expect them to necessarily be done, but the naming is a benefit. For example, I have my most played games labeled "!Title.rom" so they sit at the top. It's also nice because you can name things like "The Legend of Zelda" & "Zelda II: The Adventures of Link" to "Zelda 1 - Legend of Zelda.rom" & "Zelda 2 - Adventures of Link" so they sort together. With it using the filename you, as a user, have absolute control over the sorting.

Now, for a suggestion, if you are not wanting to change the names you have because you want to preserve the names of the files how they were when you got them I would suggest making a Originals folder somewhere & putting a Hardlink of the each file there. It won't take up more space, it will preserve the name you want, while at the same time allowing you to rename the other file to fit your sorting needs. Perfect solution, gives you what you want without taking development time or making it harder for others
