### ISSUE TITLE
Offer new subcategories for Rom hacks

### ISSUE THREAD

**Issue by thelamer** [linuxserver/emulatorjs#37]
I have not determined the exact method for menu presentation, but a user should be able to upload a single source file for popular hack scenes (smw pokemon squirrel etc) and the generation of that sub menu should be fully automated we can push a full list of art assets and bps/other.

FIle can be patched in browser before being sent to the RA cores using https://github.com/marcrobledo/RomPatcher.js in a buffer. 

The maintenance of these lists should be centralized around this repo to begin with, as far as I can tell there is no good raw feeds for ingesting them and we will need to make custom artwork and caps for them.

**Comment by nixxou** [comment]
I revise my position, i didn't know about such extensives ressources like romhacking.net, i still think multirom 7z support would be great (especially if you implement on-the-fly patching, because most patch apply to US version, so for EU players, that mean keeping multiple version of the game), but i can totally see your point about a centralized repo and on the fly patching.
