### ISSUE TITLE
2 player

### ISSUE THREAD

**Issue by Vivek230800** [linuxserver/emulatorjs#60]
Hey, I appreciate all the creators for making this. Could anyone please guide me if I want to play with my friend from 2 different locations. Can we play like that? I want to play 2 player games with her but I cannot figure out.

**Comment by Vivek230800** [comment]
Feature request: Both players see the same game but have controller 1 & 2 from different locations. That way people can play 2 player games from anywhere around the world. This would result in the best emulator in the world.

**Comment by averon420** [comment]
++++1

**Comment by thelamer** [comment]
This is dependent on upstream support: 
https://github.com/libretro/RetroArch/issues/10851
As it stands right now the emscripten retroarch cores are not a high priority which is why I forked off some of the cores I built.
I am not saying it won't happen, just that with the current tech implemented I would not get your hopes up for a short time frame.

**Comment by dd900** [comment]
@thelamer have you seen this yet?
https://github.com/ethanaobrien/emuserver

Could that be built into the docker image?
